#!/bin/bash
# ===========================================
# Deploy Falls CMS Agent to Vertex AI Agent Engine
# ===========================================
# This script handles all deployment steps:
# 1. Generates production .env in the package directory
# 2. Runs adk deploy
# 3. Extracts and displays the new agent ID
#
# Usage: ./deploy.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$SCRIPT_DIR/falls_cms_agent"

# Production configuration
PROJECT_ID="fil-mcp"
REGION="us-west1"
STAGING_BUCKET="gs://run-sources-fil-mcp-us-west1"
MCP_SERVER_URL="https://falls-mcp-server-256129779474.us-west1.run.app/sse"
RAILS_EVENTS_URL="https://staging.fallsintolove.com/api/internal/agent_events"
INTERNAL_API_TOKEN="REDACTED_TOKEN"

echo "=== Falls CMS Agent Deployment ==="
echo ""

# Step 1: Generate production .env
echo "📝 Generating production .env..."
cat > "$PACKAGE_DIR/.env" << EOF
# ===========================================
# Production Configuration (Agent Engine)
# Generated by deploy.sh - DO NOT EDIT MANUALLY
# ===========================================
GOOGLE_GENAI_USE_VERTEXAI=TRUE
GOOGLE_CLOUD_PROJECT=$PROJECT_ID
GOOGLE_CLOUD_LOCATION=$REGION

# MCP Server (Cloud Run)
MCP_SERVER_URL=$MCP_SERVER_URL

# Rails Event Push (for real-time step updates)
RAILS_EVENTS_URL=$RAILS_EVENTS_URL
INTERNAL_API_TOKEN=$INTERNAL_API_TOKEN

# OpenTelemetry for debugging
GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY=true
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true
EOF

echo "   Created $PACKAGE_DIR/.env"
echo ""

# Step 2: Activate virtual environment if not already active
if [[ -z "$VIRTUAL_ENV" ]]; then
    echo "🐍 Activating virtual environment..."
    source "$SCRIPT_DIR/.venv/bin/activate"
fi

# Step 3: Run adk deploy and capture output
echo "🚀 Deploying to Agent Engine..."
echo "   Project: $PROJECT_ID"
echo "   Region: $REGION"
echo ""

DEPLOY_OUTPUT=$(adk deploy agent_engine \
    --project="$PROJECT_ID" \
    --region="$REGION" \
    --staging_bucket="$STAGING_BUCKET" \
    --display_name="Falls CMS Agent" \
    --trace_to_cloud \
    falls_cms_agent 2>&1) || {
    echo "❌ Deployment failed!"
    echo "$DEPLOY_OUTPUT"
    exit 1
}

echo "$DEPLOY_OUTPUT"
echo ""

# Step 4: Extract the agent ID from output
# Looking for: "Created agent engine: projects/.../reasoningEngines/AGENT_ID"
AGENT_ID=$(echo "$DEPLOY_OUTPUT" | grep -oP 'reasoningEngines/\K[0-9]+' | tail -1)

if [[ -z "$AGENT_ID" ]]; then
    echo "⚠️  Could not extract agent ID from deployment output"
    echo "   Check the output above for the agent resource name"
    exit 0
fi

echo "✅ Deployment successful!"
echo ""
echo "   New Agent ID: $AGENT_ID"
echo "   Full resource: projects/256129779474/locations/$REGION/reasoningEngines/$AGENT_ID"
echo ""
echo "   Note: Rails will fetch this ID automatically at deploy time via .kamal/secrets"
echo ""

# Step 5: Update agent CLAUDE.md (for documentation purposes)
CLAUDE_MD="$SCRIPT_DIR/CLAUDE.md"
if [[ -f "$CLAUDE_MD" ]]; then
    echo "📝 Updating CLAUDE.md..."
    sed -i "s/Resource ID\`: \`[0-9]*\`/Resource ID\`: \`$AGENT_ID\`/" "$CLAUDE_MD"
    sed -i "s|reasoningEngines/[0-9]*|reasoningEngines/$AGENT_ID|" "$CLAUDE_MD"
    echo "   Updated resource ID references"
fi

echo ""
echo "=== Deployment Complete ==="
echo ""
echo "Next steps:"
echo "  1. Deploy Rails app: cd /home/fil/falls_into_love && kamal deploy"
echo "     (Agent ID will be fetched automatically from GCP)"
echo "  2. Test the assistant at https://staging.fallsintolove.com/offtrail/assistant"
echo ""
